spring.application.name=config-server
server.port=8888

# Kho cấu hình Git cục bộ
spring.cloud.config.server.git.uri=file:///C:/medical-config-repo
# Nhánh của repo cấu hình là master (không phải main)
spring.cloud.config.server.git.default-label=master
spring.cloud.config.server.git.clone-on-start=true
